- commands/action.yml
- commands/index.js
- commands/index.ts
- common/telemetry.js
- common/telemetry.ts
- metrics-collector/action.yml
- metrics-collector/index.js
- metrics-collector/index.ts
Moved metrics collection more configurable in each repo via json file and makes metrics prefix depend on repo
> Make metrics multi repo

- bump-version/index.js
- bump-version/index.ts
> Change bump version branch name

- commands/Commands.js
- commands/Commands.test.ts
- commands/Commands.ts
- commands/index.js
- commands/index.ts
- Support removal of label that have been added earlier due to changed files that no longer matches
- Add support for reopened action
> Actions based on changed files in PR update

- api/octokit.js
- api/octokit.ts
- api/testbed.js
- api/testbed.ts
- commands/Commands.js
- commands/Commands.test.ts
- commands/Commands.ts
For now, remove functionality for removing labels when changedfiles doesn't match and addLabel is defined as command.
Adds some debug statements to make it easier to debug.
> PR changedfiles fixes

- api/api.ts
- api/octokit.js
- api/octokit.ts
- api/testbed.js
- api/testbed.ts
- commands/Commands.js
- commands/Commands.test.ts
- commands/Commands.ts
- commands/action.yml
Closes #19 
Test of PR: https://github.com/grafana/github-actions-testrepo/pull/22
Test of issue: https://github.com/grafana/github-actions-testrepo/issues/23
> Automated labeling of issues and pull requests based on author org

- commands/Commands.js
- commands/Commands.test.ts
- commands/Commands.ts
- commands/action.yml
- update-changelog/index.ts
I'd like to add an ignoreList argument to the author type so we can add bots to the list and the external pr command won't add label to them.
> Add ignoreList to the author type command

- common/utils.js
- common/utils.test.ts
- common/utils.ts
- github-release/index.js
- github-release/index.ts
**Why?**
Fixes #27
This PR marks the release as pre-release based on version number format.
> feat(release): mark release as pre-release

- remove-milestone/action.yml
- remove-milestone/index.js
- remove-milestone/index.ts
For https://github.com/grafana/grafana-release/issues/76
> Chore: Create new github action to remove milestone from issue

- update-changelog/index.js
- update-changelog/index.ts
Fixes https://github.com/grafana/grafana/issues/43194
> Chore: Allow re-running the update-changelog action without closing the generated PR and branch manually

- close-milestone/action.yml
- close-milestone/index.js
- close-milestone/index.ts
For https://github.com/grafana/grafana/issues/43193
> Chore: create close milestone github action

- pr-checks/checks/BackportCheck.js
- pr-checks/checks/BackportCheck.test.ts
- pr-checks/checks/BackportCheck.ts
- pr-checks/checks/index.js
- pr-checks/checks/index.ts
Ref https://github.com/grafana/grafana-release/issues/60
Can test it out here: https://github.com/grafana/github-actions-testrepo/pull/62
> Adds backport pr check

- package.json
- yarn.lock
Resolves errors like https://github.com/grafana/grafana/runs/4856543797?check_suite_focus=true
> fixing jest types

- bump-version/index.js
- bump-version/index.ts
Trying to fix #78 - it fails sometimes on corepack install step.
> fix(78): remove corepack install, it is already there by default

- docs-target/map.js
- docs-target/map.test.ts
- docs-target/map.ts
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
> Support 'master' -> 'next' branch mapping

- README.md
- pr-checks/checks/ChangelogCheck.js
- pr-checks/checks/ChangelogCheck.test.ts
- pr-checks/checks/ChangelogCheck.ts
- pr-checks/checks/LabelCheck.js
- pr-checks/checks/LabelCheck.test.ts
- pr-checks/checks/LabelCheck.ts
- pr-checks/checks/index.js
- pr-checks/checks/index.ts
- pr-checks/types.js
- pr-checks/types.ts
Adds a specific PR check for changelog decision and validation of PR title/body. It works bases on configuration (see example config below).
1. If any of the specified `labels.matches` labels then a success status is created and does additional checks of PR title and body:
1. if PR title is not valid then a failure status is created.
1. If not i) and any of the specified `breakingChangeLabels` labels matches and the PR body doesn't find a matching `# Release notice breaking change` then a failure status is created.
1. If not i) or ii) then a success status is created.
1. If not 1) and any of the specified `skip.matches` labels matches then a success status is created.
1. If not 1) or 2) a failure status is created.
Can be tested out here: …
> Adds support for a changelog PR check

- .gitattributes
- enterprise-check/action.yml
- enterprise-check/index.js
- enterprise-check/index.ts
- repository-dispatch/action.yml
- repository-dispatch/index.js
- repository-dispatch/index.ts
The Enterprise check action is triggered by an OSS PR and checks if the same branch as the OSS one exists on Enterprise. If not, it creates one based on the same target branch (or `main` if it doesn't exist), called `pr-check-<OSS PR number>/<OSS source branch>`, to run the Drone PR pipelines on it (the branch will be deleted at the end of the build).
The Repository Dispatch action sends a `repository_dispatch` event to any repository.
> Add Enterprise check and repository dispatch actions

- backport/backport.js
- backport/backport.ts
- package.json
- yarn.lock
Will try to automatically fix conflicts in the `.betterer.results` file when backporting if that's the only conflict.
> Backport: improve handling of betterer.results file

- enterprise-check/index.js
- enterprise-check/index.ts
Github has a 256 character limit on branch names (not git though), so I figured it'd be less risky to reduce the size of the branch overall by renaming `pr-check` to `prc`.
> Add source commit to enterprise-check action

- enterprise-check/action.yml
- enterprise-check/index.ts
yea someone's gotta fix their prettier setup or something
> add the source_sha arg to the action.yml

- update-changelog/ChangelogBuilder.js
- update-changelog/ChangelogBuilder.ts
This should fix most at least some of the post-release actions.
> GitHub requires that search queries include either is:issue or is:pull-request

- api/octokit.js
- api/octokit.ts
> Update getProject query

- update-changelog/ChangelogBuilder.js
- update-changelog/ChangelogBuilder.ts
This should help avoiding running into GitHub's response limit of 1000 issues.
> Filter issues for changelog more aggressively

- update-changelog/action.yml
- update-changelog/index.js
- update-changelog/index.ts
resolves https://github.com/grafana/grafana-community-support-squad/issues/50
> publish changelog to forum

- common/telemetry.ts
Very minor change, limited to one character in one comment.
> Fix spelling of "lose"

- .devcontainer/devcontainer.json
This should also allow us to use GitHub codespaces
> Add devcontainer for streamlining local development toolchain

- pr-checks/checks/ChangelogCheck.js
- pr-checks/checks/ChangelogCheck.test.ts
- pr-checks/checks/ChangelogCheck.ts
> Changelog-check: Allow PR-titles to also have a version prefix

- backport/backport.js
- backport/backport.test.ts
- backport/backport.ts
> Backport: Set milestone on automatic backports
