grafana/grafana-github-actions

update-changelog/ReleaseNotesBuilder.js
update-changelog/ReleaseNotesBuilder.test.ts
update-changelog/ReleaseNotesBuilder.ts
update-changelog/__snapshots__/ReleaseNotesBuilder.test.ts.snap
update-changelog/index.js

It seems labels are just given as strings through the API
```
export interface Issue {
labels: string[]
...
```

Fix bug label check when building release notes

---

api/api.ts
api/octokit.js
api/octokit.ts
api/testbed.js
api/testbed.ts
commands/Commands.js
commands/Commands.test.ts
commands/Commands.ts
commands/index.js
commands/index.ts
common/Action.js
common/Action.ts
common/globmatcher.js
common/globmatcher.test.ts
common/globmatcher.ts
package-lock.json
package.json

Adds support for a new type of command named `changedfiles`. You can configure it with:
```json
[
{
"type": "changedfiles",
"matches": "**/*",
"action": "updateLabel",
"addLabel": "everything"
},
{
"type": "changedfiles",
"matches": {
"any": ["pkg/**/*", "go.mod"]
},
"action": "updateLabel",
"addLabel": "area/backend"
},
{
"type": "changedfiles",
"matches": {
"any": ["pkg/**/*", "go.mod"]
},
"action": "updateLabel",
"addLabel": "area/backend"
}
]
```
**Note:**
Currently no support for removing labels in case you revert changes of certain files.

Support actions based on changed files in PR

---

update-changelog/ReleaseNotesBuilder.js
update-changelog/ReleaseNotesBuilder.test.ts
update-changelog/ReleaseNotesBuilder.ts
update-changelog/__snapshots__/ReleaseNotesBuilder.test.ts.snap

When creating issue lines in Markdown, include the ":" following the category in the emphasized section. Fixes #21

Emphasize ":" in markdown issue lines

---

update-changelog/ReleaseNotesBuilder.js
update-changelog/ReleaseNotesBuilder.test.ts
update-changelog/ReleaseNotesBuilder.ts
update-changelog/__snapshots__/ReleaseNotesBuilder.test.ts.snap
yarn.lock

**What happened:** 
A couple of weeks ago we [introduced](https://github.com/grafana/grafana/pull/37616) the ability to prettify md files on `lint-staged` in the Grafana project. Today, after resolving conflicts between one of my branches and the main branch (That had the latest release v8.1.2), we noticed some `md` files [changed](https://github.com/grafana/grafana/pull/37741/files/602f3d363ea44ff92da1229f54468e00150d2788#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL8), they were automatically formatted from using `*` to `-` in unordered lists.
Why they were automatically formatted? This is because the code to generate our CHANGELOG and release notes is using the old prettier format for unordered list `*`, and after prettier version 2 unordered lists are now …

Prettier: Update Changelog formatting to use - instead of *

---

bump-version/index.js
bump-version/index.ts

**Why?**
We have to regenerate `yarn.lock` file every time we bump version for release. It was previously done [manually](https://github.com/grafana/grafana/pull/42297/commits/1234ecb370796d7e4191ceb22f6345fdd596e40f). This PR automates it.
**Additional changes**
- Fixed type in output of grot
**How to test**
?
Fixes #37

chore(bump-version): add yarn.lock rebuild

---

bump-version/index.js
bump-version/index.ts

Fixes #37 
yarn seems to be [failing](https://github.com/grafana/grafana/runs/4455819488?check_suite_focus=true#step:11:244) when running in grafana main repo, this should make it work (hopefully)

set YARN_ENABLE_IMMUTABLE_INSTALLS to false for generating yarn.lock

---

bump-version/index.js
bump-version/index.ts

Maybe this time we get more luck, as the last change did not really work and this step is still [failing](https://github.com/grafana/grafana/runs/4482952903?check_suite_focus=true#step:5:58).

chore(yarn-lock): should run it properly now

---

README.md
api/api.js
api/api.ts
api/octokit.js
api/octokit.ts
api/testbed.js
api/testbed.ts
commands/Commands.js
commands/Commands.test.ts
commands/Commands.ts

Add support for adding issues based on labels to "old" github projects
How to test?
- Add label "plugins" to [this issue](https://github.com/grafana/github-actions-testrepo/issues/31)
- It will add it to both projects because of [this config](https://github.com/grafana/github-actions-testrepo/blob/main/.github/issue-commands.json#L2-L18)

Add support for old projects

---

pr-checks/checks/MilestoneCheck.js
pr-checks/checks/MilestoneCheck.test.ts
pr-checks/checks/MilestoneCheck.ts

If milestoned/demilestoned is triggered this will verify that issue is not closed before fetching pull request/create commit status. An optimization. 
Test of closed PR milestoned: https://github.com/grafana/github-actions-testrepo/actions/runs/1584009891
Test of closed PR demilestoned: https://github.com/grafana/github-actions-testrepo/actions/runs/1584017352

Skip milestone check if issue is closed

---

package.json
update-changelog/testdata/_index.md
update-changelog/writeDocsFiles.js
update-changelog/writeDocsFiles.test.ts
update-changelog/writeDocsFiles.ts

**Why?**
This PR fixes a bug that sometimes a link to changelog is not added to the index file when update changelog action runs.
Reason for that is we were double checking if a link to the changelog file to be added already exists. The check although was not very strict and matched also when it should not have.
e.g. `8.4.0` matched on `8.4.0-beta1`
This PR makes the check more strict and should prevent errors like that from happening. Also added a unit test to cover this use case.
**Fixes #77**

fix(77): should add changelog properly into the index file

---

api/octokit.js
api/octokit.ts

**Why?**
`nodeId` value already exists in the Issue object that we are casting from the github event. This makes it unnecessary to fetch it again so I've removed `getItemIdFromIssueProjectNext` function and it's references.

Refactor: remove unnecessary code

---

docs-target/action.yaml
docs-target/index.js
docs-target/index.ts
docs-target/map.js
docs-target/map.test.ts
docs-target/map.ts

This PR creates a new action `DocsTarget` that will help achieve improved automation for synchronizing website documentation from upstream repositories such as [Tempo](https://github.com/grafana/tempo), to the [website](https://github.com/grafana/website) repo.  When a docs update is committed, or a new release tagged, then this action helps to determine the destination subfolder.   In summary, it will convert a branch or tag name like `release-1.2.3` into the subfolder name `v1.2`.
This action is expected to be useful to multiple projects, so adding to this shared repo makes sense.  Please see this [grafana/agent PR](https://github.com/grafana/agent/pull/1515) for related testing and discussion, and there is further internal discussion that we can link to if needed.

New action:  Documentation Target

---

common/utils.js
common/utils.ts
has-matching-release-tag/action.yaml
has-matching-release-tag/hasMatchingReleaseTag.js
has-matching-release-tag/hasMatchingReleaseTag.test.ts
has-matching-release-tag/hasMatchingReleaseTag.ts
has-matching-release-tag/index.js
has-matching-release-tag/index.ts

Produce a boolean output that has the value "true" if and only if there is a release tag that
matches the release branch.
If the provided `ref_name` is a release tag reference, the output value is "true".
If the provided `ref_name` is a release branch reference, the output value is "true" if
and only if there is a matching release tag as defined by the `release_tag_regexp`.
For release branches with a patch version, the capture groups for major, minor, and patch
versions must match between the `release_branch_with_patch_regexp` and the
`release_tag_regexp`.
For release branches without a patch version, the capture groups for major and minor
versions must match between the `release_branch_without_patch_regexp` and the
`release_tag_regexp` and the release tag must have a `0` patch version. …

Add has-matching-release-tag

---

pr-checks/checks/MilestoneCheck.js
pr-checks/checks/MilestoneCheck.test.ts
pr-checks/checks/MilestoneCheck.ts
repository-dispatch/index.ts

Improve logic in case milestoned event workflow run was cancelled so that milestone check run on labeled/unlabeled events as well. 
Reported problems with backports especially, e.g. https://github.com/grafana/grafana/pull/49573, with changelog and milestone check fails often.

PR Checks: Trigger milestone check on labeled/unlabeled actions

---

enterprise-check/index.js
enterprise-check/index.ts

Right now, when OSS commits are too close to each other and the first build isn't finished when a second commit is pushed, the Enterprise Check action can’t create the Enterprise branch (that already exists) and so can’t trigger multiple builds (failure example: https://github.com/grafana/grafana-enterprise/actions/runs/2332086035).
This can cause:
1. The developer needs to manually re-trigger the check if they made a fix for Enterprise in the second commit.
2. If the first commit doesn't break Enterprise but the second one does: we'll miss this breaking change.
This PR updates this GH action to update the branch if it already exists. This will then trigger a new Drone build.
However, the first build won't be cancelled by the new one as cancelling old builds on pushes is a global setting …

Enterprise Check: handle newer OSS commits

---

backport/backport.ts

Currently, when releasing we are including PRs which may haven't been merged. The only way to realise that, is if you open the initial PR which targets main, and see if `grot` has commented that the backport failed.
This PR adds a `backport-failed` label to PRs that were failed to be backported.
This way we can filter the PRs during the release process, and give notice to developers that they have to resolve the conflict, otherwise their change won't be included in the next version.

Backport: Add `backport-failed` label to pull requests that failed to be backported

---

backport/backport.js

Forgot to run `yarn:build` for https://github.com/grafana/grafana-github-actions/pull/110.
There should be a CI step. Will create an issue for that.

Backport: Run yarn:build for #110

---

update-changelog/index.js
update-changelog/index.ts

Based of PIR for Release 9.2.4, the changelog PR that is auto-generated has no default labels set. This PR adds the default labels. 
Example PR https://github.com/grafana/grafana/pull/58467 - you can see manually added labels in PR history

Adding default lables to changelog PR

---

backport/backport.js
backport/backport.ts
backport/index.js
backport/index.ts

**Context**:
Backporting has always been a grey area for many engineers in Grafana Labs. It's not really clear how/what to backport when we are conducting a patch release. People tend to backport many changes, which leads to patch releases not really having the hard definition of the patch release. Patch releases should be bug fixes only and some changes that are critical and have the product/managers' approval. 
**What does this pull request do**:
This pull request, post a message to the PR, notifying the author of the PR (by '@username'), each time they backport and they don't have either the `bug` or `product-approved` labels. If none of these two labels are in place, the pull request cannot be backported. 
Related convo: https://raintank-corp.slack.com/archives/C03E2AQKU2W/p16691114559 …

Backporting: Make `bug` or `product-approved` labels mandatory for backporting

---

backport/backport.js
backport/backport.ts

This PR fixes some buggy behaviour that was introduced when https://github.com/grafana/grafana-github-actions/pull/113 was merged. 
Addresses: 
* Case when no label is added. We shouldn't get any notifications.
* `no-backport` shouldn't be a valid backport action label.

Backporting: Fix buggy behaviour

---

backport/backport.js
backport/backport.ts

Bug fix based on https://github.com/grafana/grafana-github-actions/pull/115/files#r1031288511.
Thanks @dimitarvdimitrov

Backport: Break from loop if PR label matches regexp

---

backport/backport.js
backport/backport.ts

This PR adds a `missing-labels` label. This label will be automatically assigned to the pull request when there's a backport label assigned, but none of the mandatory labels `type/docs`, `type/bug`, `product-approved`.
This way we can make sure that we don't miss any backports during a release, and take immediate action.
Here's a spreadsheet with a manual case testing sequence: https://docs.google.com/spreadsheets/d/1lPxWXR01Tzlpm1Ia9ic4NEkqX8O1sXTlylF0ObJcf58/edit#gid=0

Backport: Add `missing-labels` label

---

backport/backport.js
backport/backport.ts

Right now, when a PR is closed it still looks for the payload for labels. If it doesn't find any, it returns.
This should only be true for `labeled` actions, and not for `closed`, since when we close a PR there are no labels in the payload.

Backport: Skip payload label if `action=closed`

---

enterprise-check/index.js
enterprise-check/index.ts

Update the enterprise-check action to use use source_sha argument instead of branch sha.

fix enterprise-check to use source_sha in the branch name

---

backport/backport.js
backport/backport.ts

We've seen a couple of failures, where on a `merge` action (which is actually `closed` action, plus that the PR has been merged) it seems like gh action treats it as a simple PR close without merging. Some console log will help us understand what happens here.
My thoughts are that some fields in the payload webhooks were just missed due to GH blips 🤷

Backport: Add console log for whether it's a merge action

---

api/api.js
api/api.ts
api/octokit.js
api/octokit.ts
api/testbed.js
api/testbed.ts

As of 18/01/23 GitHub has deprecated a substantial number of fields/types. This has led to a number of our project management functions failing. This PR updates the functions that will add an issue to a project and remove an issue from a project.
See details of fields removed [here](https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2023-01-18).
There may be other changes to make here..

Convert old projectNext functions to projectV2

---

commands/Commands.js
commands/Commands.test.ts
commands/Commands.ts

This new action will work in conjunction [with this modified workflow](https://github.com/grafana/grafana/pull/63158) in the grafana/grafana repo.
It will check when an issue is opened, if it was opened by a grafanista, and if any labels were added.
If a Grafanista makes an issue but adds no label, the `internal` label will be added and they will be pinged in a comment like this:
You can test drive the new action in my private repo. [Make an issue here](https://github.com/zuchka/grafana-action-test/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md) but DON'T add any labels. If you are a member of the Grafana org, you'll see a label and a comment added
**why do we need this?**
Lots of internal folks use issues as todos or reminders for themselves but don't add labels. Lots …

Issues: Add action that makes org members add a label

---

has-matching-release-tag/hasMatchingReleaseTag.js
has-matching-release-tag/hasMatchingReleaseTag.test.ts
has-matching-release-tag/hasMatchingReleaseTag.ts

Although semver requires that every bump of a major or minor version resets the patch version, it is not always the case that the tag will exist in the repository. For example, the first release might be made privately in a fork and might never be made public because of bugs or security concerns.

Match any reasonable patch version

---

backport/backport.js
backport/backport.ts

The milestone is decided by the original PR and often does not match the required milestone for a backport PR to produce a correct changelog entry.
By not automatically setting the milestone, maintainers are required to consider and set it themselves. I currently believed that edge cases around target branch to milestone mapping (such as out of date milestones) mean that this human step is less error prone than code would be.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Do not add milestone to backport PRs

---

backport/backport.js
backport/backport.ts

@grafana/grafana-delivery has to backport CI changes all the time and picking `product-approved` simply feels weird here 🙂

Allow backporting of type/ci issues

---

common/telemetry.js
common/telemetry.ts
release-notes-appender/FileAppender.js
release-notes-appender/FileAppender.ts
release-notes-appender/action.yml
release-notes-appender/index.js
release-notes-appender/index.ts
release-notes-appender/release.js
release-notes-appender/release.ts

Release notes are a subset of a CHANGELOG, highlighting the most important and exciting features in a release. Currently, when doing a release of Loki, the person doing the release needs to comb through all the PRs since the last release and decide what's most important, which is a time consuming and error prone process. This action will allow a contributor to add the `add-to-release-notes` label to a PR. When that PR is merged, this will automatically create a PR into the repo that appends the PRs title and number to a file that is a placeholder for the next versions release. This provides 2 advantages.
1. We amortize the release notes collation process over the whole release cycle.
2. The created PR provides an opportunity for the team to consider if the item is actually release notes …

Add release notes appender action

---

backport/backport.js
backport/backport.test.ts
backport/backport.ts

In practice, resolving docs backports that are non-trivial takes longer than manually creating a backport.
@imatwawana, @chri2547: No need to review, just requesting so that you both know that the auto conflict resolution behavior has been reverted.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Stop trying to automatically resolve conflicts for documentation

---

bump-version/index.js
bump-version/index.ts

This should avoid compatibility issues between lerna@latest and what we use within grafana/grafana.

Bump-version: Use local lerna version

---

backport/backport.js
backport/backport.test.ts
backport/backport.ts
backport/index.js
backport/index.ts

With this PR we should be able to prevent information loss (at least for the automatically generated backports) around the changelog if a backport contains the `add to changelog` label. The PR body is copied to also have the various breaking-changes- and deprecation-notices available.
This PR does not yet tackle manually created backports, though.
The PR body now contains the old notice that this is backport of some other PR and also (after a horizontal ruler) the original body. Labels are copied and all the `backport .*` ones are removed.
These will come next. I have some ideas around how to tackle that problem (like having grot react to the `backport` table but those ideas are not yet completely finalized.
---
Fixes #147

Backport: Copy body and all labels from original PR

---

backport/backport.js
backport/backport.ts

Basically, if the original pull-request had an empty body, the body of the backport looked like this:
```
Backport ... from ...
---
null
```
With this change it should now only look like this:
```
Backport ... from ...
```

Backport: Do not copy null-bodies to the backports

---

backport/backport.js
backport/backport.ts

This should avoid running into "milestone check: failed" situations more often. The idea is to emulate the order that the GitHub CLI uses when creating a PR with a milestone.

Backport: Set milestone first

---

backport/backport.js
backport/backport.test.ts
backport/backport.ts

This PR extends the "failed backport" comment with the labels set by the original PR (as done in the automated PR) and also copies the description over using `gh pr view`:
```bash
git fetch
git switch --create backport-36-to-v10.0.x origin/v10.0.x
git cherry-pick -x 27d3466ba916670a8f3ae0277d5224da900d7a61
git add . && git cherry-pick --continue
gh pr view 36 --json body --template 'Backport 27d3466ba916670a8f3ae0277d5224da900d7a61 from #36{{ "\n\n---\n\n" }}{{ index . "body" }}' > .pr-body.txt
gh pr create --title "[v10.0.x] Update README.md" --body-file .pr-body.txt --label "type/docs" --label "no-changelog" --label "backport" --base v10.0.x --milestone 10.0.x --web
git push --set-upstream origin backport-36-to-v10.0.x
git switch main
git branch -D backport-36-to-v10.0.x
```
If the …

Backport: gh pr command with labels and original body

---

backport/backport.js
backport/backport.ts

Instead of having a file containing the PR body hang around on the filesystem we can store the body string in a shell variable and pass it as `stdin` to the `pr create` command.

Fix: clean up pr-body.txt

---

bump-version/action.yml
bump-version/index.js
bump-version/index.ts

The idea of this change is to allow projects to define additional code that should be executed *before* the PR with the updated files is created. This way things like the `make gen-cue` command can be executed by the grafana/grafana project.
For a project to add such custom commands, it has to include a Make target for it and then set it as `precommit_make_target` input to this action. E.g.:
```yaml
- name: Run bump version
uses: ./actions/bump-version
with:
precommit_make_target: gen-cue
```
This relates to https://github.com/grafana/grafana/issues/73880.

Bump-version: Add precommit hook

---

backport/backport.js
backport/backport.test.ts
backport/backport.ts

This will also include the `git push` instruction to the manual backport guide and move some of the other instructions around a bit.
```
To backport manually, run these commands in your terminal:
```bash
git fetch
git switch --create backport-123-to-v10.0.x origin/v10.0.x
git cherry-pick -x 123456
git add . && git cherry-pick --continue
```
If you have the [GitHub CLI](https://cli.github.com/) installed:
```bash
git push --set-upstream origin backport-123-to-v10.0.x
PR_BODY=$(gh pr view 123 --json body --template 'Backport 123456 from #123{{ \"\\n\\n---\\n\\n\" }}{{ index . \"body\" }}')
echo \"${PR_BODY}\" | gh pr create --title \"[v10.0.x] hello world\" --body-file - --label \"backport\" --label \"no-changelog\" --base v10.0.x --milestone 10.0.x --web
```
Or, if you don't have the …
```

fix(backport): Add git push to manual backport instructions

---

has-matching-release-tag/hasMatchingReleaseTag.js
has-matching-release-tag/hasMatchingReleaseTag.ts
has-matching-release-tag/index.js
has-matching-release-tag/index.ts

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
Will help diagnose confusing behavior with the workflow

Add debug logging and use core outputs
